postgres:
  container_name: bike_delivery
  image: postgres:11-alpine
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'docker'
    POSTGRES_PASSWORD: 'docker'
    POSTGRES_DB: 'bike_delivery'